# syntax=docker/dockerfile:1.7

ARG DEV_BASE_IMAGE=aces-dev-base:latest
FROM ${DEV_BASE_IMAGE}

ENV POETRY_VIRTUALENVS_CREATE=false \
    ACES_PROJECT_DIR=/workspace/aces \
    ACES_BOOTSTRAP_PROJECT=1 \
    ACES_BOOTSTRAP_FROM_IMAGE=0

WORKDIR /workspace
